### ISSUE TITLE
面试宝典项目的API登录接口的用户名密码是什么？

### ISSUE THREAD

**Issue by lansheng8929** [zhousg/zhousg#2]
面试宝典项目的API登录接口的用户名密码是什么？
<img width="659" alt="截屏2024-07-22 15 44 54" src="https://github.com/user-attachments/assets/deb4029a-5b43-4ef9-a1b9-bb6d5e6609d6">

**Comment by zhousg** [comment]
@State
  mobile: string = 'hmheima'
  @State
  code: string = 'Hmheima%123'
